### PR TITLE
fix(cli): set options.config to loaded custom config for processing

### LINKED ISSUE #227: BUG: Using a Custom Preset Config Not Working With `conventional-changelog-cli`
# Problem

@stevemao I created a custom preset by forking the conventional-changelog-angular. It can get it produce the expected output by dropping it into `/usr/local/lib/node_modules/conventional-changelog-cli/node_modules`. It is, however, not working with the --config option of the CLI, which is my preferred way of using it. It simply outputs the changelog without any expected sections, e.g. Added, Removed, etc.

# Steps to reproduce
 
1. Install the preset in an existing project with a few commits `npm install --save-dev conventional-changelog-stalinkay`
 2. Use `conventional-changelog --config ./node_modules/conventional-changelog-stalinkay/index.js -r 0`

# Expected Behavior

I expect changelog to contain the custom sections when using a custom --config but none are present when using the steps above.

### PR DESCRIPTION
**Pull request by RayBenefield**
Closes #227 

Setting this up allows the core to properly load the configuration (handling promises or however the config is delivered). Otherwise nothing is loaded and a default config is used instead.

### CODE REVIEW

**Comment by RayBenefield** [comment]
Working on a test for this.

**Comment by RayBenefield** [comment]
Alright test added. I had to add `q` to setup a proper promise.

**Comment by hbetts** [comment]
Thank you for filing this @RayBenefield!

I hadn't even realized this wasn't getting passed through to `core`.

@stevemao does this change seem alright with you?

File: packages/conventional-changelog-cli/cli.js [hunk 1]
```diff
@@ -112,6 +112,7 @@ try {
 
   if (flags.config) {
     config = require(resolve(process.cwd(), flags.config));
+    options.config = config;
```
Comment (hbetts) [inline packages/conventional-changelog-cli/cli.js]: Could you just assign the required value to `options.config` and then use `options.config` elsewhere? That way there is only a single source of truth for the loaded configuration.

File: packages/conventional-changelog-cli/test/fixtures/promise-config.js [hunk 2]
```diff
@@ -0,0 +1,8 @@
+'use strict';
+var Q = require('q');
```
Comment (hbetts) [inline packages/conventional-changelog-cli/test/fixtures/promise-config.js]: Is `q` needed? Could we just use native promises?

**Comment by hbetts** [comment]
This might seem like an odd question, but if the configuration wasn't getting loaded, how do the other tests pass?

File: packages/conventional-changelog-cli/cli.js (hunk 1 above)
Comment (RayBenefield) [reply packages/conventional-changelog-cli/cli.js]: I'm not quite sure I follow. The main reason that I'm setting `options.config` here is because if config is a promise then `writerOpts`, `parserOpts`, and `gitRawCommitsOpts` won't be populated and can't be sent downstream. The other option is to resolve the promise in `conventional-changelog-cli` from the config, and then handle assignment of all of the opts after the resolution and then call `conventionalChangelog`.

The config gets resolved as a promise here: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-core/lib/merge-config.js#L93

I modeled this change off of: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog/index.js#L9

That is where presets are loaded to be resolved as a promise. And I don't see any other place that sets `options.config` so the only conflict that would appear would be if a custom config AND a preset was set. In this case, perhaps extending the custom config over top of the preset is something that should be done.

There are several ways to slice it and I'll leave it to you guys to decide as I'm not as familiar with the code base.

File: packages/conventional-changelog-cli/test/fixtures/promise-config.js (hunk 2 above)
Comment (RayBenefield) [reply packages/conventional-changelog-cli/test/fixtures/promise-config.js]: I guess we could use native promises. I only used `q` to match the rest of the code base and I'm also not familiar with native promises availability in given versions of `node` so I didn't want to muddle any further. This is only like my third pull request and the others were simple readme changes. lol...

**Comment by RayBenefield** [comment]
@hbetts the other tests are passing because when `writerOpts`, `parserOpts`, and `gitRawCommitsOpts` are extracted from `config` in the `cli` script, they exist when it isn't a promise, and don't exist when it is a promise. The resolution of a promisified config doesn't happen until it reaches `conventional-changlog-core`. Presets work fine because `options.config` is set after the `cli` script and is expected to be resolved in `conventional-changelog-core`.

File: packages/conventional-changelog-cli/test/fixtures/promise-config.js (hunk 2 above)
Comment (hbetts) [reply packages/conventional-changelog-cli/test/fixtures/promise-config.js]: > This is only like my third pull request and the others were simple readme changes.

Ah, well thank you for taking the next step with this change.

> I only used q to match the rest of the code base 

That's fine. Since `conventional-changelog` only supports Node 4 and higher, so using native promises is perfectly fine, and my preference when possible (avoids third-party packages for native features where possible, lowering the overall overhead of installing `conventional-changelog`).

Though I'm not sure how much the other core maintainers of `conventional-changelog` prefer maintaining consistency within files.

File: packages/conventional-changelog-cli/cli.js (hunk 1 above)
Comment (hbetts) [reply packages/conventional-changelog-cli/cli.js]: Thank you for the explanation. I didn't realize you were relying on the promise resolution behavior of `conventional-changelog-core` to resolve `options.config`. This line makes a lot more sense now.

**Comment by hbetts** [comment]
👍 This change looks fine to me.

**Comment by machour** [comment]
Just tried `conventional-changelog-cli` for the first time and wanted to use my own templates .. thank you so much @RayBenefield for this PR, I was going nuts 😄

**Comment by hbetts** [comment]
cc @stevemao and @bcoe for a last review before I accept this change.

**Comment by hbetts** [comment]
@RayBenefield @machour, version `1.3.9` of `conventional-changelog-cli` has been released.

Successfully published the following packages:
 - conventional-changelog-angular@1.6.2
 - conventional-changelog-cli@1.3.9
 - conventional-changelog-core@2.0.1
 - conventional-changelog-ember@0.3.2
 - conventional-changelog@1.1.11
 - conventional-commits-parser@2.1.1
 - conventional-recommended-bump@1.2.1
 - gulp-conventional-changelog@1.1.11
 - standard-changelog@1.0.9

**Comment by RayBenefield** [comment]
WOOT!!! First real PR to an external project. Thanks @hbetts for the experience. 👍

**Comment by stevemao** [comment]
Sorry @FGRibreau, missed your issue https://github.com/conventional-changelog-archived-repos/conventional-changelog-cli/issues/9. it should be fixed by this. Thanks @RayBenefield !
